[22:09:27 - main - INFO] Waiting for JIT...
Traceback (most recent call last):
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/main.py", line 40, in <module>
    app.run(main)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/main.py", line 32, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/train.py", line 102, in train_and_evaluate
    model.state = model.step(model.state, batch)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/models.py", line 195, in step
    grads = grad(self.loss)(state.params, state.weights, batch, *args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/models.py", line 146, in loss
    losses = self.losses(params, batch, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/models.py", line 87, in losses
    layer_grad_directions[layer] = float(jax.device_get(lax.stop_gradient(grad_direction)).tolist() )
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape float64[]
The tolist() method was called on traced array with shape float64[].
The error occurred while tracing the function loss at /Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/models.py:143 for jit. This value became a tracer due to JAX operations on these lines:

  operation a:f64[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] b
    from line /Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/models.py:31:12 (AllenCahn.u_net)

  operation a:f64[512,1] = broadcast_in_dim[broadcast_dimensions=(0,) shape=(512, 1)] b
    from line /Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/models.py:31:12 (AllenCahn.u_net)

  operation a:f64[] = convert_element_type[new_dtype=float64 weak_type=False] b
    from line /Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/archs.py:74:34 (PeriodEmbs.__call__)

  operation a:f64[] = convert_element_type[new_dtype=float64 weak_type=False] b
    from line /Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/archs.py:74:56 (PeriodEmbs.__call__)

  operation a:f64[] = convert_element_type[new_dtype=float64 weak_type=False] b
    from line /Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/archs.py:414:25 (ModifiedMlp.__call__)

(Additional originating lines are not shown.)
The error occurred while tracing the function loss at /Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/models.py:143 for jit. This value became a tracer due to JAX operations on these lines:

  operation a:f64[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] b
    from line /Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/models.py:31:12 (AllenCahn.u_net)

  operation a:f64[512,1] = broadcast_in_dim[broadcast_dimensions=(0,) shape=(512, 1)] b
    from line /Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/models.py:31:12 (AllenCahn.u_net)

  operation a:f64[] = convert_element_type[new_dtype=float64 weak_type=False] b
    from line /Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/archs.py:74:34 (PeriodEmbs.__call__)

  operation a:f64[] = convert_element_type[new_dtype=float64 weak_type=False] b
    from line /Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/archs.py:74:56 (PeriodEmbs.__call__)

  operation a:f64[] = convert_element_type[new_dtype=float64 weak_type=False] b
    from line /Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/archs.py:414:25 (ModifiedMlp.__call__)

(Additional originating lines are not shown.)

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
