[21:18:01 - main - INFO] Waiting for JIT...
[21:18:07 - main - INFO] --------------------------
[21:18:07 - main - INFO] Iter:   0    Time: 5.615
[21:18:07 - main - INFO] -----------  -------------
[21:18:07 - main - INFO] ics_loss     3.909e-01
[21:18:07 - main - INFO] res_loss     7.404e+00
[21:18:07 - main - INFO] l2_error     1.294e+00
I1012 21:18:08.130784 8441426496 checkpoints.py:570] Saving checkpoint at step: 2
I1012 21:18:08.131097 8441426496 checkpoints.py:658] Using Orbax as backend to save Flax checkpoints. For potential troubleshooting see: https://flax.readthedocs.io/en/latest/guides/training_techniques/use_checkpointing.html#orbax-as-backend-troubleshooting
I1012 21:18:08.131217 8441426496 abstract_checkpointer.py:35] orbax-checkpoint version: 0.6.4
I1012 21:18:08.131387 8441426496 checkpointer.py:189] [process=0] Started saving checkpoint to /Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/default/ckpt/checkpoint_2.
Traceback (most recent call last):
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/main.py", line 40, in <module>
    app.run(main)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/main.py", line 32, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/train.py", line 127, in train_and_evaluate
    save_checkpoint(model.state, path, keep=config.saving.num_keep_ckpts)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/utils.py", line 45, in save_checkpoint
    checkpoints.save_checkpoint(workdir, state, step=step, keep=keep)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/flax/training/checkpoints.py", line 693, in save_checkpoint
    orbax_checkpointer.save(
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/orbax/checkpoint/checkpointer.py", line 201, in save
    raise ValueError(f'Destination {directory} already exists.')
ValueError: Destination /Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/default/ckpt/checkpoint_2 already exists.
